import { vazir } from "@/utils/fonts";
import "./globals.css";

export const metadata = {
  title: "Divar clone website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>{children}</body>
    </html>
  );
}
